### ISSUE TITLE
Create a book from it with mdbook

### ISSUE THREAD

**Issue by simonsan** [Divy1211/AoE2DE_UGC_Guide#1]
https://rust-lang.github.io/mdBook/index.html

I can help setting it up and actually also generating the github pages within a github action.
Should be pretty straight forward given the fact, that you have everything in markdown already.

You can copy the `.github/workflows` from https://github.com/rust-unofficial/patterns for example

**Comment by simonsan** [comment]
Oops, haven't seen the link on the right and that you have a page already up. :)

**Comment by Divy1211** [comment]
Hey! thanks for the offer hehe, glad to know someone was interested in helping with the project! I don't actually have a link to the page in the readme itself, so I see why you happened to miss it 11
