### ISSUE TITLE
new info to be added to the guide

### ISSUE THREAD

**Issue by AnCap-Boykisser** [Divy1211/AoE2DE_UGC_Guide#15]
Break off Combat flag 64: Monaspas have this flag in combination with 32. Idk what it does. perhaps a receive-version of 32?
attribute 116: Hoplites use this to give each other armor. why isn't 8 used instead? also, I can only get melee armor to work when copying this ability to another unit.

**Comment by gd1446056618** [comment]
Break off Combat flag  32 seems to make aura effects apply on self.  The search wait time flag please check the  Update 128442
first.

**Comment by AnCap-Boykisser** [comment]
you mean Break off Combat flag *64* makes the aura effect apply on itself? because 32 merely activates the aura in the first place. that's how Caravanserais for exmaple work. they don't apply the speed buff to themselves.

and the new attributes, yeah they're explained on https://www.ageofempires.com/news/age-of-empires-ii-definitive-edition-update-128442/#ReleaseNotesTop thank you :3
but Hoplites don't even have an aura with attribute 117, so why do they give each other pierce armor?

**Comment by gd1446056618** [comment]
Yeah, I reversed flag32 and flag64. I check the AGE, (Mercenary) Hoplites do not ive each other pierce armor. But, Elite Hoplites do.

**Comment by AnCap-Boykisser** [comment]
ah yes, I overlooked that

**Comment by Divy1211** [comment]
flag 64 flips the target of the task 155 to the source unit itself.
