### ISSUE TITLE
Counting units

### ISSUE THREAD

**Issue by M3Marty** [Divy1211/AoE2DE_UGC_Guide#3]
Hi there 👋🏼. I have some issues with counting units. I want to make civians require food and army require food and gold to function. "Visual scripting" in aoe map editor have condition element Own objects which check if source player own that many or more of specific object. I'd like to call it from xs and using binary search (since its not much of them any way) get mind about exactly number of archery units or civian units player have.
Is it any way to do it? I have some more specific issues but i believe solving of this one will answers others.
P.S.: Sorry for my english.

**Comment by Divy1211** [comment]
Hi there! Unfortunately, normal effects/conditions can't be called through XS right now. Hopefully the game devs add this feature at some point though!
Also, for future reference an issue is not the right channel to ask questions, please join our discord [through this invite link](https://discord.gg/rNa6cUC76W) to ask questions from here on out! I will go ahead and close this issue
